# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ddf806b1b42b160871535fd54ea27ca48c6ec367099edbd1eeeea0216909499f77a97821ca0d03d6bf6eea90049e42ad4a55c8ab0c898dac783cf0baf8d933

test:
  secret_key_base: 74eb0c1aa94efd1d9392315ade3b5a6c55d7faf1b6124ea26d5e06106a62da9ad8b5742666e7947972ec02b9a95fec9691468ca3688f076c700e9059ded41294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
